language: node_js

node_js:
  - "8"

before_install:
  - "git clone https://github.com/frappe/frappejs && cd frappejs"
  - "npm install -g yarn"
  - "yarn"

script:
  - "yarn link && yarn link frappejs"
  - "yarn run test"
